# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_s_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_shuxue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='s_yuwen',
            field=models.IntegerField(null=True),
        ),
    ]
