# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180530_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
