# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_img',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
