# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='login_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
